
--INFORME 1:
CREATE OR REPLACE VIEW CLIENTESXREGION AS 
SELECT REG.NOMBRE_REGION,
       SUM(CASE 
               WHEN MONTHS_BETWEEN(SYSDATE, CLI.FECHA_INSCRIPCION) > 240
               THEN 1
               ELSE 0
           END) AS CANTIDAD_CLIENTES_ANTIGUOS,
       COUNT(CLI.NUMRUN) AS TOTAL_CLIENTES
FROM CLIENTE CLI
INNER JOIN REGION REG ON REG.COD_REGION = CLI.COD_REGION
GROUP BY REG.NOMBRE_REGION
ORDER BY CANTIDAD_CLIENTES_ANTIGUOS;



CREATE INDEX IDX_REGION ON CLIENTE (COD_REGION);   

CREATE INDEX IDX_CLI_REGION ON CLIENTE (COD_REGION, NUMRUN);

--INFORME 2:

--Consulta con operador SET
SELECT TO_CHAR(SYSDATE, 'DD-MM-YYYY') AS FECHA
        ,COD_TPTRAN_TARJETA AS CODIGO
        ,UPPER(NOMBRE_TPTRAN_TARJETA) AS DESCRIPCION
        ,ROUND(AVG(MONTO_TRANSACCION)) AS MONTO_PROMEDIO_TRANSACCION
FROM(
    SELECT DISTINCT CTT.NRO_TARJETA
          ,CTT.NRO_TRANSACCION
          --,TTC.FECHA_TRANSACCION
          ,TTC.COD_TPTRAN_TARJETA
          ,TTC.MONTO_TRANSACCION
          ,TTT.NOMBRE_TPTRAN_TARJETA
          ,TRUNC((EXTRACT(MONTH FROM CTT.FECHA_VENC_CUOTA)+1)/7) +1 AS SEMESTRE
         --,SUM(TTC.MONTO_TOTAL_TRANSACCION/CTT.NRO_CUOTA)/COUNT(CTT.NRO_TARJETA)
         
    FROM  CUOTA_TRANSAC_TARJETA_CLIENTE  CTT 
    INNER JOIN TRANSACCION_TARJETA_CLIENTE TTC ON TTC.NRO_TARJETA=CTT.NRO_TARJETA AND TTC.NRO_TRANSACCION = CTT.NRO_TRANSACCION
    INNER JOIN TIPO_TRANSACCION_TARJETA TTT ON TTT.COD_TPTRAN_TARJETA = TTC.COD_TPTRAN_TARJETA
   
    
    MINUS
    
     SELECT DISTINCT CTT.NRO_TARJETA
          ,CTT.NRO_TRANSACCION
          --,TTC.FECHA_TRANSACCION
          ,TTC.COD_TPTRAN_TARJETA
          ,TTC.MONTO_TRANSACCION
          ,TTT.NOMBRE_TPTRAN_TARJETA
          ,TRUNC((EXTRACT(MONTH FROM CTT.FECHA_VENC_CUOTA)+1)/7) +1 AS SEMESTRE
         --,SUM(TTC.MONTO_TOTAL_TRANSACCION/CTT.NRO_CUOTA)/COUNT(CTT.NRO_TARJETA)
         
    FROM  CUOTA_TRANSAC_TARJETA_CLIENTE  CTT 
    INNER JOIN TRANSACCION_TARJETA_CLIENTE TTC ON TTC.NRO_TARJETA=CTT.NRO_TARJETA AND TTC.NRO_TRANSACCION = CTT.NRO_TRANSACCION
    INNER JOIN TIPO_TRANSACCION_TARJETA TTT ON TTT.COD_TPTRAN_TARJETA = TTC.COD_TPTRAN_TARJETA
    WHERE TRUNC((EXTRACT(MONTH FROM CTT.FECHA_VENC_CUOTA)+1)/7) +1 = 1
   )
GROUP BY COD_TPTRAN_TARJETA
        ,NOMBRE_TPTRAN_TARJETA   
    ORDER BY  MONTO_PROMEDIO_TRANSACCION   ;

--Consulta con Subconsulta - Inserción tabla SELECCION_TIPO_TRANSACCION
INSERT INTO SELECCION_TIPO_TRANSACCION
SELECT TO_CHAR(SYSDATE, 'DD-MM-YYYY') AS FECHA
        ,TTT.COD_TPTRAN_TARJETA AS COD_TIPO_TRANSAC
        ,UPPER(TTT.NOMBRE_TPTRAN_TARJETA) AS NOMBRE_TIPO_TRANSAC
        ,ROUND(AVG(TTC.MONTO_TRANSACCION))  AS MONTO_PROMEDIO --INDICÓ EN EL FORO QUE ERA EL MONTO TOTAL, SIN EMBARGO DECIDÍ USAR EL MONTO PORQUE DE ESTE MODO COINCIDEN LOS VALORES CON LA IMÁGEN DEL DOCUMENTO
FROM TRANSACCION_TARJETA_CLIENTE TTC
INNER JOIN (SELECT DISTINCT NRO_TARJETA --JOIN CON UNA SUBCONSULTA
            ,NRO_TRANSACCION
        FROM  CUOTA_TRANSAC_TARJETA_CLIENTE               
        WHERE  EXTRACT(MONTH FROM FECHA_VENC_CUOTA) > 5    ) CTTC ON CTTC.NRO_TARJETA = TTC.NRO_TARJETA AND CTTC.NRO_TRANSACCION = TTC.NRO_TRANSACCION
INNER JOIN TIPO_TRANSACCION_TARJETA TTT ON TTT.COD_TPTRAN_TARJETA = TTC.COD_TPTRAN_TARJETA
GROUP BY TTT.COD_TPTRAN_TARJETA,TTT.NOMBRE_TPTRAN_TARJETA
ORDER BY MONTO_PROMEDIO;

SELECT * FROM SELECCION_TIPO_TRANSACCION;

--Actualización de tabla TIPO_TRANSACCION_TARJETA 
UPDATE TIPO_TRANSACCION_TARJETA TTT SET TTT.TASAINT_TPTRAN_TARJETA = TTT.TASAINT_TPTRAN_TARJETA-0.01
WHERE EXISTS (
    SELECT 1
    FROM SELECCION_TIPO_TRANSACCION TT
    WHERE TT.COD_TIPO_TRANSAC = TTT.COD_TPTRAN_TARJETA
);

